### ISSUE TITLE
"install.sh" using `readlink` which doesn't work with flag `-f`

### ISSUE THREAD

**Issue by alaadahmed** [gasparch/vim-ide-elixir#4]
I tried many times to install your plugin on __macOS__ following your README but I always get this error:
```
readlink: illegal option -- f
usage: readlink [-n] [file ...]
usage: dirname path
It needs wget to download stuff from internets
```
I checked man of `readlink` and found that you can't use it with flag `-f` which stands for `Format` and I used instead of `readlink` => `stat`, it worked finally! Thanks for your efforts, really awesome plugin.

**Comment by gasparch** [comment]
Thank you a lot for being one of the first adopters ;) 

I'll fix it to work on MacOS too. Please report any problems and feature requests with environment, because I'm using it on Linux only.
